# Generated by Django 6.0.3 on 2026-03-22 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('used_by', models.ManyToManyField(blank=True, to='accounts.customer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='discount_percent_inrange_0_to_100')],
            },
        ),
    ]
