[project]
name = "bookworm"
version = "0.1.0"
description = "bookstore website for CS 3773-002, Spring 2026"
authors = [
    {name = "g3se"}
]
license = "CC0-1.0"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django (>=6.0.2,<6.1.0)",
    "django-two-factor-auth (>=1.18.1,<1.19.0)",
    "python-dotenv (>=1.2.1,<1.3.0)",
    "gunicorn (>=25.1.0,<25.2.0)",
    "pillow (>=12.1.1,<13.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false


[tool.ruff]
line-length = 80
exclude = ["**/migrations"]
