# Generated by Django 6.0.3 on 2026-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_cartitem_index_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default='123 Line St, Some City, Some State 98765', max_length=511),
            preserve_default=False,
        ),
    ]
