# Generated by Django 6.0.4 on 2026-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='[No full name]', max_length=255),
            preserve_default=False,
        ),
    ]
