# Generated by Django 6.0.2 on 2026-04-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2047)),
                ('genre', models.CharField(max_length=127)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
            options={
                'verbose_name': 'Book details',
                'verbose_name_plural': 'Book details',
            },
        ),
        migrations.CreateModel(
            name='StockBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookdetails')),
            ],
            options={
                'verbose_name': 'Book in stock',
                'verbose_name_plural': 'Books in stock',
            },
        ),
    ]
