# Generated by Django 6.0.3 on 2026-03-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdetails',
            options={'verbose_name': 'Book details', 'verbose_name_plural': 'Book details'},
        ),
        migrations.AlterModelOptions(
            name='stockbook',
            options={'verbose_name': 'Book in stock', 'verbose_name_plural': 'Books in stock'},
        ),
    ]
