# Generated by Django 6.0.3 on 2026-03-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookdetails_options_alter_stockbook_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='genre',
            field=models.CharField(default='Fiction', max_length=127),
            preserve_default=False,
        ),
    ]
