# Generated by Django 6.0.4 on 2026-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookdetails_cover_img_bookdetails_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbook',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
